# -*- coding: utf-8 -*-
"""Modelbuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACH17aHh5N0pTqSCKzvU-iNF5gFukPsQ
"""

import pandas as pd

df=pd.read_csv('/content/Salary_Dataset_DataScienceLovers.csv')

df

df.info()

df.isnull().sum()

company_name_mode = df['Company Name'].mode()[0]
df['Company Name'].fillna(company_name_mode, inplace=True)

df.isnull().sum()

df.drop_duplicates()

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

# Instantiate a new LabelEncoder for each column to ensure proper transformation
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
print('Categorical columns in df have been label encoded.')

print('DataFrame after Label Encoding:')
display(df.head())
print('\nUpdated DataFrame Info:')
df.info()

X = df.drop('Salary', axis=1)
y = df['Salary']

X = df.drop('Salary', axis=1)
y = df['Salary']
print('Input variables (X):')
display(X.head())
print('\nOutput variable (y):')
display(y.head())

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
print('Linear Regression model trained successfully.')

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

from sklearn.linear_model import LinearRegression

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

print('Linear Regression model trained successfully.')

from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)
print('Decision Tree Regressor model trained successfully.')

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)
print('Random Forest Regressor model trained successfully.')

from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)
print('K-Nearest Neighbors Regressor model trained successfully.')

from sklearn.svm import SVR

svm_model = SVR()
svm_model.fit(X_train, y_train)
print('Support Vector Machine Regressor model trained successfully.')

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pandas as pd

# Initialize lists to store metrics
model_names = []
r2_scores = []
maes = []
mses = []

# Evaluate Linear Regression model
if 'linear_model' in locals():
    y_pred_lr = linear_model.predict(X_test)
    model_names.append('Linear Regression')
    r2_scores.append(r2_score(y_test, y_pred_lr))
    maes.append(mean_absolute_error(y_test, y_pred_lr))
    mses.append(mean_squared_error(y_test, y_pred_lr))

# Evaluate Decision Tree Regressor model
if 'dt_model' in locals():
    y_pred_dt = dt_model.predict(X_test)
    model_names.append('Decision Tree Regressor')
    r2_scores.append(r2_score(y_test, y_pred_dt))
    maes.append(mean_absolute_error(y_test, y_pred_dt))
    mses.append(mean_squared_error(y_test, y_pred_dt))

# Evaluate Random Forest Regressor model
if 'rf_model' in locals():
    y_pred_rf = rf_model.predict(X_test)
    model_names.append('Random Forest Regressor')
    r2_scores.append(r2_score(y_test, y_pred_rf))
    maes.append(mean_absolute_error(y_test, y_pred_rf))
    mses.append(mean_squared_error(y_test, y_pred_rf))

# Evaluate K-Nearest Neighbors Regressor model
if 'knn_model' in locals():
    y_pred_knn = knn_model.predict(X_test)
    model_names.append('K-Nearest Neighbors Regressor')
    r2_scores.append(r2_score(y_test, y_pred_knn))
    maes.append(mean_absolute_error(y_test, y_pred_knn))
    mses.append(mean_squared_error(y_test, y_pred_knn))

# Evaluate Support Vector Machine Regressor model
if 'svm_model' in locals():
    y_pred_svm = svm_model.predict(X_test)
    model_names.append('Support Vector Machine Regressor')
    r2_scores.append(r2_score(y_test, y_pred_svm))
    maes.append(mean_absolute_error(y_test, y_pred_svm))
    mses.append(mean_squared_error(y_test, y_pred_svm))

# Create a DataFrame to display the results
metrics_df = pd.DataFrame({
    'Model': model_names,
    'R2 Score': r2_scores,
    'MAE': maes,
    'MSE': mses
})

display(metrics_df.sort_values(by='R2 Score', ascending=False))

import pickle
import pandas as pd

# Re-train Linear Regression model to ensure it's available for evaluation
# (This assumes X_train, y_train are available from previous steps)
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
print('Linear Regression model re-trained successfully.')

# Re-evaluate all models to get an up-to-date metrics_df
# (This code block is adapted from cell 36f83f8c)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

model_names = []
r2_scores = []
maes = []
mses = []

# Evaluate Linear Regression model
y_pred_lr = linear_model.predict(X_test)
model_names.append('Linear Regression')
r2_scores.append(r2_score(y_test, y_pred_lr))
maes.append(mean_absolute_error(y_test, y_pred_lr))
mses.append(mean_squared_error(y_test, y_pred_lr))

# Evaluate Decision Tree Regressor model
if 'dt_model' in locals(): # Ensure dt_model exists from previous training
    y_pred_dt = dt_model.predict(X_test)
    model_names.append('Decision Tree Regressor')
    r2_scores.append(r2_score(y_test, y_pred_dt))
    maes.append(mean_absolute_error(y_test, y_pred_dt))
    mses.append(mean_squared_error(y_test, y_pred_dt))

# Evaluate Random Forest Regressor model
if 'rf_model' in locals(): # Ensure rf_model exists from previous training
    y_pred_rf = rf_model.predict(X_test)
    model_names.append('Random Forest Regressor')
    r2_scores.append(r2_score(y_test, y_pred_rf))
    maes.append(mean_absolute_error(y_test, y_pred_rf))
    mses.append(mean_squared_error(y_test, y_pred_rf))

# Evaluate K-Nearest Neighbors Regressor model
if 'knn_model' in locals(): # Ensure knn_model exists from previous training
    y_pred_knn = knn_model.predict(X_test)
    model_names.append('K-Nearest Neighbors Regressor')
    r2_scores.append(r2_score(y_test, y_pred_knn))
    maes.append(mean_absolute_error(y_test, y_pred_knn))
mses.append(mean_squared_error(y_test, y_pred_knn))

# Evaluate Support Vector Machine Regressor model
if 'svm_model' in locals(): # Ensure svm_model exists from previous training
    y_pred_svm = svm_model.predict(X_test)
    model_names.append('Support Vector Machine Regressor')
    r2_scores.append(r2_score(y_test, y_pred_svm))
    maes.append(mean_absolute_error(y_test, y_pred_svm))
    mses.append(mean_squared_error(y_test, y_pred_svm))

metrics_df = pd.DataFrame({
    'Model': model_names,
    'R2 Score': r2_scores,
    'MAE': maes,
    'MSE': mses
})

display(metrics_df.sort_values(by='R2 Score', ascending=False))

# Identify the best model based on R2 Score
best_model_row = metrics_df.loc[metrics_df['R2 Score'].idxmax()]
best_model_name = best_model_row['Model']

# Get the actual best model object
best_model = None
if best_model_name == 'Linear Regression':
    best_model = linear_model
elif best_model_name == 'Decision Tree Regressor':
    best_model = dt_model
elif best_model_name == 'Random Forest Regressor':
    best_model = rf_model
elif best_model_name == 'K-Nearest Neighbors Regressor':
    best_model = knn_model
elif best_model_name == 'Support Vector Machine Regressor':
    best_model = svm_model

if best_model is not None:
    # Save the best model to a .pkl file
    filename = f'{best_model_name.replace(" ", "_").lower()}_model.pkl'
    with open(filename, 'wb') as file:
        pickle.dump(best_model, file)
    print(f'Best model ({best_model_name}) saved successfully to {filename}')
else:
    print('Could not identify or save the best model.')

print('Re-executing data preparation cells to ensure correct encoding and split:')
# Re-apply Label Encoding to ensure df is fully numerical before splitting
# This code was already in ec54bd36, executing it here explicitly
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
print('Categorical columns in df have been label encoded again.')

# Now split into X and y from the fully encoded df
X = df.drop('Salary', axis=1)
y = df['Salary']

print('\nDataFrame dtypes after encoding and before X, y split:')
display(df.dtypes)
print('\nInput variables (X) dtypes:')
display(X.dtypes)
print('\nOutput variable (y) head:')
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('Train-test split performed successfully.')

print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

print('\nNow you can try running the model training cell `79458dda` again.')